### ISSUE TITLE
Ability to regenerate with new settings on entry/section save

### ISSUE THREAD

**Issue by jannisborgers** [madmadmad/slugger#3]
Great plugin, great way to send out campaigns etc!

After I had 30 entries, I noticed I needed them without i and l (lowercase L) characters, because they will be sent via mail and need to be human-readable. I changed the settings, but the entry slugs are persistent.

Is there a way to regenerate the slugs for entries? Ideally not per entry, but when saving the section (which resaves all its entries)? Or within the plugin settings?

**Comment by smockensturm** [comment]
Hey there. Hmm nothing automatic, I'm afraid.

Here's a possible workaround though.

You might try decoding all the entries' slugs (via a template), take note of all the original ID's, turn slugger off, change all your slugs manually, turn the plugin back on (after modifying the alphabet you want to use) and re-save the channel.

I dunno though. I'm not entirely sure the plugin is setup to work on existing entries, just new ones.

**Comment by jannisborgers** [comment]
@smockensturm Thank you! This is the kind of manual workaround that I had in mind as well. Luckily, I don’t have to save any work here, this is before the launch of the campaign. If I understand you correctly, you want to turn the plugin off, change the slugs manually, turn the plugin back on and save the section, which will re-save the entries.

Unfortunately Slugger doesn’t fire when re-saving entries. It looks like the plugin only does its thing once, when a new entry is added. Never on re-save.

I think a re-save functionality would really benefit users in any case where the plugin settings have to be updated after entries have been added.

**Comment by smockensturm** [comment]
> I think a re-save functionality would really benefit users in any case where the plugin settings have to be updated after entries have been added.

Agreed. We'll look at how that works down the road.
