### ISSUE TITLE
Internal Server Error on save of exisiting entires & on creation of new entries

### ISSUE THREAD

**Issue by davidtabor** [madmadmad/slugger#4]
Installed Slugger
1. Turned on hashing for one section.
2. Edit entry in that section to force hashed slug
 - Internal Server Error on save
3. Turn off hashing
 - No Error
4. Re-Enable Hashing and attempt saving entry
 - Internal Server Error
5. Read Docs and notice that you say to create new entry after enabling hashing
 - Internal Server Error when try to create new Entry
6. Disable Hashing and attempt creating entry
 - No Error
7. I have Dynamic Titles enabled for this section. I've tried disabling them, switching between longform and shortform Twig syntax, changing the twig shortcuts and filters, removing special characters etc. I'm using the following Dynamic Title format: {firstName} {lastName|slice(0,1)} - {preferredTitle}

Not really sure how to proceed from here. I've tried all the combinations I can think of. Please advise!

Relevant Error log from 'web.log' file:

2020-01-20 22:14:52 [-][1][-][error][verbb\cpnav\services\CpNavService::modifyCpNav] Trying to get property 'id' of non-object
2020-01-20 22:14:51 [-][1][-][info][application] $_GET = [
    'p' => 'admin/settings/plugins/slugger'
]

System Info screenshots attached:
<img width="829" alt="Screen Shot 2020-01-20 at 10 38 06 PM" src="https://user-images.githubusercontent.com/11561153/72773638-c5279580-3bd5-11ea-8ca9-323eaf876f5c.png">
<img width="579" alt="Screen Shot 2020-01-20 at 10 38 18 PM" src="https://user-images.githubusercontent.com/11561153/72773639-c5279580-3bd5-11ea-990e-df913c9b51f0.png">

**Comment by smockensturm** [comment]
Hello @davidtabor Thanks for the report. We'll take a look. If you have time to clear caches and zip up and send a fresh set of logs, that would be helpful.

**Comment by davidtabor** [comment]
@smockensturm Thanks for the reply. This is my first time submitting files for a bug report like this. What files do you need? Thanks!

**Comment by smockensturm** [comment]
They will be in ./storage/logs

If you clear your cache in the Craft control panel (not necessary, but will make things easier to find), then pop your Slugger error / entry, we’ll get a fresh set of logs.

Whatever you can come up with will be helpful, I’m sure.

**Comment by davidtabor** [comment]
Steps taken:
1. Clear Craft Caches from dashboard
2. Make Sure Slugger is enabled
3. Try to create new Entry
 - Internal Server Error
4. Edit existing Entry and try to save
 - Internal Server Error
5. Pull logs folder

Thanks for your help!

Attachments: Zipped Logs Folder, screenshot of Slugger settings page. 
[logs - Slugger Error.zip](https://github.com/madmadmad/slugger/files/4093325/logs.-.Slugger.Error.zip)
<img width="1065" alt="Slugger Settings page" src="https://user-images.githubusercontent.com/11561153/72837310-4b86ba80-3c5c-11ea-8c3a-8f0c4e2b24df.png">

**Comment by smockensturm** [comment]
Hey David.

Can't duplicate this. Sorry. And see nothing in the logs to indicate Slugger is throwing an error.

In fact, from your original post, we see this:

> 2020-01-20 22:14:52 [-][1][-][error][verbb\cpnav\services\CpNavService::modifyCpNav] Trying to get property 'id' of non-object

Appears an error is being thrown by a Verbb plugin, Control Panel Nav probably?

**Comment by smockensturm** [comment]
Closing this for now @davidtabor Send us more info when you can.
