### ISSUE TITLE
Packagist has older version

### ISSUE THREAD

**Issue by keyurshah** [madmadmad/slugger#7]
Hello,

It looks like packagist has the older version (1.0.2) of the library and is causing a problem to install the latest version (1.0.3)

https://packagist.org/packages/madhouse/slugger

Thanks.

**Comment by smockensturm** [comment]
Thank you. Updated.

**Comment by keyurshah** [comment]
Hello, Can you please update again. Looks packagist has 1.0.3 currently.

Thanks.
