### ISSUE TITLE
Accessing "Settings" not possible due to Exception

### ISSUE THREAD

**Issue by MartinSchmid2409** [madmadmad/slugger#8]
I have Craft 3.4.30 with Yii 2.0.35 and Slugger 1.0.3 and PHP 7.3.5.

When I have installed the plugin (which works) and try to access "Settings" I get a ReflectionException.

Please see attached screenshot for all details.

![Screenshot_2020-12-10 Invalid Configuration – yii base InvalidConfigException](https://user-images.githubusercontent.com/1540028/101775296-89e4cc80-3aef-11eb-9bf1-993024d66ecd.png)

**Comment by smockensturm** [comment]
Hello Martin.

This is a recent change for composer 2 compat. You can read more about it here.

https://github.com/madmadmad/slugger/issues/6

May I suggest resaving your entries? You can do this via command line.

`./craft resave/entries`

options...

`--section=mySectionHandle --type=myEntryTypeHandle --update-search-index`
